meat_substitutions = {
    "beef stock": { "substitution": "vegetable stock", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "beef broth": { "substitution": "vegetable broth", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "ground beef": { "substitution": "brown lentils", "ratio": 1.0, "unit": "cup", "sentence": " cup(s) of dried, uncooked brown lentils", "comment": "dried, uncooked", "additions": { "prep_time": 15, "ingredients": ["3 cups water"], "steps": ["Place the lentils and water in a large saucepan.", "Bring to a rapid simmer, then reduce the heat and simmer for about 15 minutes until the lentils are tender but still hold their shape. Drain any excess liquid and set aside for later use."] }},
    "new york strip steak": { "substitution": "cauliflower steak", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "new york strip": { "substitution": "cauliflower steak", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "steak": { "substitution": "cauliflower steak", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "beef patties": { "substitution": "bean patties", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "beef": { "substitution": "tempeh", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "chicken stock": { "substitution": "vegetable stock", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "chicken broth": { "substitution": "vegetable broth", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "chicken breast": { "substitution": "seitan slice", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "chicken thigh": { "substitution": "seitan slice", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "chicken wing": { "substitution": "seitan slice", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "chicken leg": { "substitution": "seitan slice", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "chicken": { "substitution": "seitan", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "pork chop": { "substitution": "cauliflower steak", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "pork belly": { "substitution": "chanterelles mushrooms", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "pork bones": { "substitution": "vegetable scraps", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "pork": { "substitution": "jackfruit", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "lamb": { "substitution": "eggplant", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "goat": { "substitution": "tempeh", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "turkey": { "substitution": "tofurky", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "veal": { "substitution": "beets", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "bone broth": { "substitution": "vegetable broth", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "bones": { "substitution": "vegetable scraps", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "lobster": { "substitution": "vegan lobster", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "crab": { "substitution": "vegan crab", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "shrimp": { "substitution": "vegan shrimp", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "fish": { "substitution": "vegan fish", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "anchovies": { "substitution": "vegan fish", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "worcestershire sauce": { "substitution": "vegetarian worcestershire sauce", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
}

vegetable_substitutions = {
    "tofu": { "substitution": "shrimp", "ratio": 1.0, "unit": None, "sentence": None, "12 shrimp, shelled and deveined": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "seitan": { "substitution": "chicken", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "bean patties": { "substitution": "beef patties", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "black beans": { "substitution": "ground beef", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "brown lentils": { "substitution": "ground beef", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "soy burger-style crumbles": { "substitution": "ground beef", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "tempeh": { "substitution": "beef", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "tofurky": { "substitution": "turkey", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "vegetarian ": { "substitution": "", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "vegan ": { "substitution": "", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
}

unhealthy_substitutions = {
    "butter": { "substitution": "coconut oil", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "margarine": { "substitution": "coconut oil", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "shortening": { "substitution": "coconut oil", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "lard": { "substitution": "coconut oil", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "palm oil": { "substitution": "olive oil", "ratio": 1.0, "unit": None, "sentence": None, "comment": "extra virgin", "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "corn oil": { "substitution": "olive oil", "ratio": 1.0, "unit": None, "sentence": None, "comment": "extra virgin", "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "canola oil": { "substitution": "olive oil", "ratio": 1.0, "unit": None, "sentence": None, "comment": "extra virgin", "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "peanut oil": { "substitution": "olive oil", "ratio": 1.0, "unit": None, "sentence": None, "comment": "extra virgin", "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "vegetable oil": { "substitution": "olive oil", "ratio": 1.0, "unit": None, "sentence": None, "comment": "extra virgin", "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "white rice": { "substitution": "brown rice", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "all purpose flour": { "substitution": "whole wheat flour", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "all-purpose flour": { "substitution": "whole wheat flour", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "white flour": { "substitution": "whole wheat flour", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "white bread": { "substitution": "whole wheat bread", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "white sugar": { "substitution": "honey", "ratio": 0.5, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "brown sugar": { "substitution": "coconut sugar", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "high-fructose corn syrup": { "substitution": "honey", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "corn syrup": { "substitution": "honey", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "maple syrup": { "substitution": "honey", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "simple syrup": { "substitution": "honey", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "breadcrumbs": { "substitution": "crushed nuts", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 5, "ingredients": [], "steps": []} },
    "panko breadcrumbs": { "substitution": "crushed nuts", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 5, "ingredients": [], "steps": []} },
    "bread crumbs": { "substitution": "crushed nuts", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 5, "ingredients": [], "steps": []} },
    "panko bread crumbs": { "substitution": "crushed nuts", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 5, "ingredients": [], "steps": []} },
    "sour cream": { "substitution": "greek yogurt", "ratio": 1.0, "unit": None, "sentence": None, "comment": "plain", "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "mayonnaise": { "substitution": "greek yogurt", "ratio": 1.0, "unit": None, "sentence": None, "comment": "plain", "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "cream cheese": { "substitution": "cottage cheese", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "heavy cream": { "substitution": "coconut cream", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "ground beef": { "substitution": "ground turkey", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "beef stock": { "substitution": "vegetable stock", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "beef broth": { "substitution": "vegetable broth", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "beef chuck roast": { "substitution": "turkey thigh", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "beef chuck": { "substitution": "turkey thigh", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "beef": { "substitution": "turkey", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "ground pork": { "substitution": "ground turkey", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "pork sausage": { "substitution": "turkey sausage", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "pork": { "substitution": "turkey", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "bacon": { "substitution": "turkey bacon", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "whole milk": { "substitution": "skim milk", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
}

healthy_substitutions = {
    "coconut oil": { "substitution": "butter", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "olive oil": { "substitution": "canola oil", "ratio": 1.0, "unit": None, "sentence": None, "comment": "extra virgin", "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "brown rice": { "substitution": "white rice", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "whole wheat flour": { "substitution": "all-purpose white flour", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "chickpea flour": { "substitution": "all-purpose white flour", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "buckwheat flour": { "substitution": "all-purpose white flour", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "oat flour": { "substitution": "all-purpose white flour", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "corn flour": { "substitution": "all-purpose white flour", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "rice flour": { "substitution": "all-purpose white flour", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "whole wheat bread": { "substitution": "white bread", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "multigrain bread": { "substitution": "white bread", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "honey": { "substitution": "high fructose corn syrup", "ratio": 0.5, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "maple syrup": { "substitution": "high fructose corn syrup", "ratio": 0.5, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "agave": { "substitution": "high fructose corn syrup", "ratio": 0.5, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "brown sugar": { "substitution": "molasses", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} }, 
    "coconut sugar": { "substitution": "brown sugar", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "monk fruit sweetener": { "substitution": "white sugar", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "monkfruit sweetener": { "substitution": "white sugar", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "monk fruit extract": { "substitution": "white sugar", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "monkfruit extract": { "substitution": "white sugar", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "monk fruit": { "substitution": "white sugar", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "monkfruit": { "substitution": "white sugar", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "stevia": { "substitution": "white sugar", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "lowfat milk": { "substitution": "whole milk", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "skim milk": { "substitution": "whole milk", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "2% milk": { "substitution": "whole milk", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "soymilk": { "substitution": "whole milk", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "oatmilk": { "substitution": "whole milk", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "almondmilk": { "substitution": "whole milk", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "cashewmilk": { "substitution": "whole milk", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "soy milk": { "substitution": "whole milk", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "oat milk": { "substitution": "whole milk", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "almond milk": { "substitution": "whole milk", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "cashew milk": { "substitution": "whole milk", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "avocado": { "substitution": "mayonnaise", "ratio": 1.0, "unit": None, "sentence": None, "comment": "plain", "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "cottage cheese": { "substitution": "cream cheese", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "coconut cream": { "substitution": "heavy cream", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "vegetable stock": { "substitution": "beef stock", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "vegetable broth": { "substitution": "beef broth", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "turkey thigh": { "substitution": "beef chuck", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "ground turkey": { "substitution": "ground pork", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "turkey sausage": { "substitution": "pork sausage", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "turkey": { "substitution": "pork", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "turkey bacon": { "substitution": "bacon", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "salmon steak": { "substitution": "pork chop", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "salmon": { "substitution": "pork", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "soy sauce": { "substitution": "worcestershire sauce", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "reduced-sodium soy sauce": { "substitution": "soy sauce", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
}

south_asian_substitutions = {
    "corn oil": { "substitution": "ghee", "ratio": 1.0, "unit": None, "sentence": " ghee", "comment": "extra virgin", "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "canola oil": { "substitution": "ghee", "ratio": 1.0, "unit": None, "sentence": None, "comment": "extra virgin", "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "vegetable oil": { "substitution": "ghee", "ratio": 1.0, "unit": None, "sentence": None, "comment": "extra virgin", "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "olive oil": { "substitution": "ghee", "ratio": 1.0, "unit": None, "sentence": None, "comment": "extra virgin", "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "butter": { "substitution": "ghee", "ratio": 1.0, "unit": None, "sentence": None, "comment": "extra virgin", "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "margarine": { "substitution": "ghee", "ratio": 1.0, "unit": None, "sentence": None, "comment": "extra virgin", "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "shortening": { "substitution": "ghee", "ratio": 1.0, "unit": None, "sentence": None, "comment": "extra virgin", "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "lard": { "substitution": "ghee", "ratio": 1.0, "unit": None, "sentence": None, "comment": "extra virgin", "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "white rice": { "substitution": "basmati rice", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "brown rice": { "substitution": "basmati rice", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "black rice": { "substitution": "basmati rice", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "sticky rice": { "substitution": "basmati rice", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "rice": { "substitution": "basmati rice", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "jalapeno pepper": { "substitution": "guntur chili pepper", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "jalapeño pepper": { "substitution": "guntur chili pepper", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "jalapeno": { "substitution": "guntur chili pepper", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "jalapeño": { "substitution": "guntur chili pepper", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "habañero pepper": { "substitution": "kashmiri red chili pepper", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "habanero pepper": { "substitution": "kashmiri red chili pepper", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "habañero": { "substitution": "kashmiri red chili pepper", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "habanero": { "substitution": "kashmiri red chili pepper", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "black pepper": { "substitution": "black cardamom", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "cayenne pepper": { "substitution": "chili powder", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "paprika": { "substitution": "curry powder", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "italian seasoning": { "substitution": "garam masala", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "parsley": { "substitution": "bay leaf", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "thyme": { "substitution": "cumin", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "rosemary": { "substitution": "fennel seeds", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "oregano": { "substitution": "ground coriander", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "nutmeg": { "substitution": "cinnamon", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "cilantro": { "substitution": "green chili pepper", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "onion powder": { "substitution": "tumeric", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "chicken stock": { "substitution": "vegetable stock", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "chicken broth": { "substitution": "vegetable broth", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "chicken bouillon": { "substitution": "star anise", "ratio": 1.0, "unit": "pod", "sentence": " pod star anise", "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "bouillon": { "substitution": "star anise", "ratio": 1.0, "unit": "pod", "sentence": " pod star anise", "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "beef stock": { "substitution": "vegetable stock", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "beef broth": { "substitution": "vegetable broth", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "ground beef": { "substitution": "ground goat", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "new york strip steak": { "substitution": "goat steak", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "new york strip": { "substitution": "goat steak", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "steak": { "substitution": "goat steak", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "beef patties": { "substitution": "goat patties", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "beef": { "substitution": "goat", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "black bean": { "substitution": "black lentils", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "kidney bean": { "substitution": "split red lentils", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "pinto bean": { "substitution": "brown lentils", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
    "feta cheese": { "substitution": "paneer", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
}

# "": { "substitution": "", "ratio": 1.0, "unit": None, "sentence": None, "comment": None, "additions": { "prep_time": 0, "ingredients": [], "steps": []} },
